# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FNSNXM4OKB_JNicstRm4zIlvO063_EG1
"""

import pandas as pd
from plotnine import (
    ggplot,
    aes,
    geom_point,
    geom_smooth,
    facet_wrap,
    facet_grid,
    labs,
    theme,
    scale_x_log10,
    scale_y_log10,

)
from plotnine.data import diamonds

# Importar o conjunto de dados
# O enunciado diz "disponível no website", mas como o contexto anterior
# mencionou, ele está convenientemente na biblioteca plotnine.data
df_diamonds = diamonds

# Vamos inspecionar os dados
print(df_diamonds.head())

# CÉLULA 1: INSTALAR E CARREGAR DADOS
!pip install plotnine

from plotnine.data import diamonds
print(diamonds.head())

# CÉLULA 2: ATIVIDADE 1

# Importa as funções necessárias para este gráfico
from plotnine import ggplot, aes, geom_point, geom_smooth, scale_x_log10, scale_y_log10, labs
from plotnine.data import diamonds

# Cria o gráfico (note o 'diamonds' direto)
plot1 = (
    ggplot(diamonds, aes(x='carat', y='price'))

    # 1. Pontos com transparência (alpha)
    + geom_point(alpha=0.1)

    # 2. Linha de tendência (usando 'lm', que não precisa de nada extra)
    + geom_smooth(method='lm', color='blue')

    # 3. Escalas logarítmicas
    + scale_x_log10()
    + scale_y_log10()

    # 4. Rótulos
    + labs(
        title='Relação entre Preço e Peso (Carat) dos Diamantes',
        x='Peso (Carat) - Escala Log',
        y='Preço (USD) - Escala Log'
    )
)

# 5. Mostra o gráfico
plot1

# CÉLULA 3: ATIVIDADE 2

# Importa as funções necessárias para este gráfico
from plotnine import ggplot, aes, geom_point, geom_smooth, scale_x_log10, scale_y_log10, labs, facet_wrap, theme
from plotnine.data import diamonds

# Cria o gráfico
plot2 = (
    ggplot(diamonds, aes(x='carat', y='price'))
    + geom_point(alpha=0.1)
    + scale_x_log10()
    + scale_y_log10()

    # Linha de tendência linear
    + geom_smooth(method='lm', color='red')

    # Cria os painéis separados para cada 'cut'
    + facet_wrap('~ cut', ncol=5)

    + labs(
        title='Relação Preço vs. Peso, dividida por Qualidade de Corte',
        x='Peso (Carat) - Escala Log',
        y='Preço (USD) - Escala Log'
    )
    + theme(figure_size=(14, 5))
)

# 5. Mostra o gráfico
plot2

# CÉLULA 4: ATIVIDADE 3

# Importa as funções necessárias para este gráfico
from plotnine import ggplot, aes, geom_point, scale_x_log10, scale_y_log10, labs, facet_grid, theme
from plotnine.data import diamonds

# Cria o gráfico
plot3 = (
    ggplot(diamonds, aes(x='carat', y='price', color='clarity')) # Mapeia 'clarity' para a cor

    + geom_point(alpha=0.1)
    + scale_x_log10()
    + scale_y_log10()

    # Cria a matriz de gráficos (Cor vs. Corte)
    + facet_grid('color ~ cut')

    + labs(
        title='Relação Preço vs. Peso por Corte, Cor e Clareza',
        x='Peso (Carat) - Escala Log',
        y='Preço (USD) - Escala Log',
        color='Clareza'
    )
    + theme(figure_size=(16, 12))
)

# 5. Mostra o gráfico
plot3